### ISSUE TITLE
"Alert to phone numbers" field is missing from configuration

### ISSUE THREAD

**Issue by Onfire7** [wsergio/watchmen-plugin-twilio#1]
I feel like I am missing something, I got it installed and setup, but I don't have a "Alert to phone numbers" field in the service configuration. Also, I can't seem to find any code in the plugin that would create this. Do I need to make a change to watchmen to get it to show up?

**Comment by wsergio** [comment]
I haven't found a suitable way yet to alter the watchmen's views from within the plugin. 
I'm trying to find a solution, but until then, you can add the field manually in file `webserver/views/service-edit.html` after line 99:
```
<div class="form-group">
    <label for="service-alertToPhoneNumbers" class="col-sm-2 control-label">Alert to phone numbers</label>
    <div class="col-sm-6">
        <input type="text" ng-model="service.alertPhoneNumbers" type="checkbox" class="form-control" id="service-alertToPhoneNumbers" placeholder="+40758638441">
    </div>
    <div class="descr col-sm-4">List of phone numbers to alert to</div>
</div>
```

Try that and, if everything's okay, let me know & I'll update the README with this workaround until I find a proper solution.

Related issue (watchmen project): [https://github.com/iloire/watchmen/issues/68](https://github.com/iloire/watchmen/issues/68)

**Comment by Onfire7** [comment]
THIS IS AWESOME!
Adding it worked like a charm, thanks so much!

As for the proper way to implement it, I feel like maybe it could be as simple as adding a json file to the plugin with a description of the fields to add or something... That way multiple plugins can be added without having issues with editing the same template file.

Just make a object describing the page then merge in the ones from all the plugins and run it through the template maybe?

**Comment by wsergio** [comment]
Glad to hear it worked.
Thanks for the suggestions.
I'll close the issue for now.
